# Generated by Django 5.0 on 2026-02-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип договора (полностью)', max_length=255, verbose_name='Тип договора (полностью)')),
                ('short_name', models.CharField(help_text='Тип договора (кратко)', max_length=255, verbose_name='Тип договора (кратко)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RnDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вид работы', max_length=255, verbose_name='Вид работы')),
                ('short_name', models.CharField(help_text='Вид работы (полностью)', max_length=255, verbose_name='Вид работы (полностью)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Типы НИОКР',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Номер ГК / договора', max_length=255, null=True, verbose_name='Номер ГК / договора')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_type', to='rnd.contracttype', verbose_name='Тип ГК / договора')),
            ],
            options={
                'verbose_name': 'Государственный контракт / Договор',
                'verbose_name_plural': 'Государственные контракты / Договоры',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RnD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(help_text='Договор, к которому относится НИОКР', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnd_contracts', to='rnd.contract', verbose_name='ГК / договор')),
            ],
            options={
                'verbose_name': 'НИОКР',
                'verbose_name_plural': 'НИОКР',
                'ordering': ['contract__number'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Шифр работы в соответствии с государственным контрактом или договором', max_length=255, null=True, verbose_name='Шифр работы')),
                ('title', models.CharField(blank=True, help_text='Наименование темы работы в соответствии с государственным контрактом или договором', max_length=500, null=True, verbose_name='Тема работы')),
                ('purpose', models.TextField(blank=True, help_text='Основная цель работы', null=True, verbose_name='Цель работы')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Отметка, является ли эта версия актуальной', verbose_name='Актуальная версия')),
                ('contract', models.ForeignKey(help_text='Договор, к которому относится техническое задание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_specifications', to='rnd.contract', verbose_name='ГК / договор')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Ссылка на предыдущую версию ТЗ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='rnd.technicalspecification', verbose_name='Предыдущая версия')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnd_types', to='rnd.rndtype', verbose_name='Вид работы')),
            ],
            options={
                'verbose_name': 'Техническое задание',
                'verbose_name_plural': 'Технические задания',
                'ordering': ['code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RnDTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения задачи', verbose_name='Порядковый номер')),
                ('description', models.TextField(help_text='Подробное описание задачи', verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('technical_specification', models.ForeignKey(help_text='Техническое задание, к которому относится задача', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to='rnd.technicalspecification', verbose_name='Техническое задание')),
            ],
            options={
                'verbose_name': 'Задача работы',
                'verbose_name_plural': 'Задачи работы',
                'ordering': ['technical_specification', 'order'],
                'unique_together': {('technical_specification', 'order')},
            },
        ),
    ]
