# Generated by Django 5.0 on 2026-02-08 09:10

import django.db.models.deletion
import rnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название типа документа', max_length=255, verbose_name='Тип документа (полностью)')),
                ('short_name', models.CharField(help_text='Краткое название типа документа для отображения в списках', max_length=100, verbose_name='Тип документа (кратко)')),
                ('is_supplementary', models.BooleanField(default=False, help_text='Отметьте для типов, которые являются дополнительными соглашениями', verbose_name='Является дополнительным соглашением')),
                ('description', models.TextField(blank=True, help_text='Подробное описание типа документа', null=True, verbose_name='Описание')),
                ('parent_type', models.ForeignKey(blank=True, help_text='Для доп. соглашений укажите тип основного договора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_types', to='rnd.contracttype', verbose_name='Родительский тип договора')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
                'ordering': ['is_supplementary', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Уникальный номер документа', max_length=255, unique=True, verbose_name='Номер документа')),
                ('name', models.CharField(blank=True, help_text='Полное наименование документа', max_length=500, null=True, verbose_name='Наименование документа')),
                ('signed_date', models.DateField(help_text='Дата подписания документа', verbose_name='Дата подписания')),
                ('effective_date', models.DateField(help_text='Дата, с которой документ действует', verbose_name='Дата вступления в силу')),
                ('status', models.CharField(choices=[('active', 'Действующий'), ('suspended', 'Приостановлен'), ('completed', 'Завершен'), ('terminated', 'Расторгнут')], default='active', max_length=20, verbose_name='Статус документа')),
                ('document', models.FileField(blank=True, help_text='Отсканированная копия документа', null=True, upload_to='contracts/%Y/%m/', verbose_name='Скан документа')),
                ('description', models.TextField(blank=True, help_text='Описание документа или внесенных изменений', null=True, verbose_name='Описание/комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_contract', models.ForeignKey(blank=True, help_text='Основной договор, к которому относится данный документ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='rnd.contract', verbose_name='Основной договор')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Предыдущая версия этого документа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='rnd.contract', verbose_name='Предыдущая версия')),
                ('type', models.ForeignKey(help_text='Тип документа (договор, доп. соглашение и т.д.)', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rnd.contracttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-signed_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RnDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название типа НИОКР', max_length=255, verbose_name='Название типа работ')),
                ('short_name', models.CharField(help_text='Краткое обозначение типа работ', max_length=100, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание типа работ', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип НИОКР',
                'verbose_name_plural': 'Типы НИОКР',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='rnd_rndtype_name_5ec224_idx')],
            },
        ),
        migrations.CreateModel(
            name='RnD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(help_text='Уникальный идентификатор НИОКР для внешних ссылок. Заполняется вручную.', max_length=100, unique=True, verbose_name='UUID (идентификатор)')),
                ('code', models.CharField(help_text='Уникальный шифр работы согласно контракту', max_length=100, verbose_name='Шифр работы')),
                ('title', models.CharField(help_text='Полное наименование темы работы', max_length=500, verbose_name='Тема работы')),
                ('purpose', models.TextField(blank=True, help_text='Основные цели и задачи работы', null=True, verbose_name='Цель работы')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('suspended', 'Приостановлена'), ('completed', 'Завершена'), ('contract_terminated', 'Контракт расторгнут')], default='in_progress', max_length=20, verbose_name='Статус НИОКР')),
                ('last_contract_status', models.CharField(blank=True, choices=[('active', 'Действующий'), ('suspended', 'Приостановлен'), ('completed', 'Завершен'), ('terminated', 'Расторгнут')], editable=False, max_length=20, null=True, verbose_name='Последний статус договора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Основной договор, по которому ведется НИОКР', on_delete=django.db.models.deletion.PROTECT, related_name='rnd_works', to='rnd.contract', verbose_name='Основной договор')),
                ('type', models.ForeignKey(help_text='Тип научно-исследовательских работ', on_delete=django.db.models.deletion.PROTECT, to='rnd.rndtype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'НИОКР',
                'verbose_name_plural': 'НИОКР',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Отсканированное техническое задание в формате PDF', upload_to=rnd.models.TechnicalSpecification.get_upload_path, verbose_name='Файл ТЗ')),
                ('version', models.CharField(default='1.0', help_text='Версия ТЗ (например: 1.0, 2.1, Исправленная)', max_length=20, verbose_name='Версия ТЗ')),
                ('is_active', models.BooleanField(default=True, help_text='Является ли эта версия ТЗ действующей', verbose_name='Актуальная версия')),
                ('description', models.TextField(blank=True, help_text='Что изменилось в этой версии ТЗ', null=True, verbose_name='Описание изменений')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract_document', models.ForeignKey(help_text='Документ, которым утверждено ТЗ (договор или доп. соглашение)', on_delete=django.db.models.deletion.PROTECT, related_name='technical_specifications', to='rnd.contract', verbose_name='Документ-основание')),
                ('rnd', models.ForeignKey(help_text='НИОКР, к которому относится ТЗ', on_delete=django.db.models.deletion.CASCADE, related_name='technical_specifications', to='rnd.rnd', verbose_name='НИОКР')),
            ],
            options={
                'verbose_name': 'Техническое задание',
                'verbose_name_plural': 'Технические задания',
                'ordering': ['rnd', '-is_active', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RnDTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения задачи в списке', verbose_name='Порядковый номер')),
                ('description', models.TextField(help_text='Подробное описание задачи и требований к выполнению', verbose_name='Описание задачи')),
                ('is_completed', models.BooleanField(default=False, help_text='Отметка о выполнении задачи', verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rnd.rnd', verbose_name='НИОКР')),
                ('source_specification', models.ForeignKey(blank=True, help_text='Техническое задание, из которого взята задача (для справки)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='rnd.technicalspecification', verbose_name='Источник (ТЗ)')),
            ],
            options={
                'verbose_name': 'Задача НИОКР',
                'verbose_name_plural': 'Задачи НИОКР',
                'ordering': ['rnd', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='contracttype',
            index=models.Index(fields=['short_name'], name='rnd_contrac_short_n_88d292_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttype',
            index=models.Index(fields=['is_supplementary'], name='rnd_contrac_is_supp_bdf157_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['number'], name='rnd_contrac_number_29b29b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['type'], name='rnd_contrac_type_id_07ab47_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='rnd_contrac_status_e5a4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['main_contract'], name='rnd_contrac_main_co_338dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='rnd',
            index=models.Index(fields=['status'], name='rnd_rnd_status_96bbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='rnd',
            index=models.Index(fields=['code'], name='rnd_rnd_code_9b1d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='rnd',
            index=models.Index(fields=['contract', 'status'], name='rnd_rnd_contrac_33805a_idx'),
        ),
        migrations.AddIndex(
            model_name='rnd',
            index=models.Index(fields=['uuid'], name='rnd_rnd_uuid_931462_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rnd',
            unique_together={('contract', 'code')},
        ),
        migrations.AddIndex(
            model_name='technicalspecification',
            index=models.Index(fields=['rnd', 'is_active'], name='rnd_technic_rnd_id_a948de_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalspecification',
            index=models.Index(fields=['contract_document'], name='rnd_technic_contrac_9fa4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='rndtask',
            index=models.Index(fields=['rnd', 'is_completed'], name='rnd_rndtask_rnd_id_407bcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rndtask',
            unique_together={('rnd', 'order')},
        ),
    ]
