# Generated by Django 5.0 on 2026-02-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название типа договора', max_length=255, verbose_name='Тип договора (полностью)')),
                ('short_name', models.CharField(help_text='Краткое название типа договора для отображения в списках', max_length=100, verbose_name='Тип договора (кратко)')),
                ('description', models.TextField(blank=True, help_text='Подробное описание типа договора', null=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
                'ordering': ['short_name'],
                'indexes': [models.Index(fields=['short_name'], name='rnd_contrac_short_n_88d292_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Уникальный номер контракта/договора', max_length=255, unique=True, verbose_name='Номер контракта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('type', models.ForeignKey(help_text='Тип контракта (государственный, договор и т.д.)', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rnd.contracttype', verbose_name='Тип контракта')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RnDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название типа НИОКР', max_length=255, verbose_name='Название типа работ')),
                ('short_name', models.CharField(help_text='Краткое обозначение типа работ', max_length=100, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание типа работ', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип НИОКР',
                'verbose_name_plural': 'Типы НИОКР',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='rnd_rndtype_name_5ec224_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный шифр работы согласно контракту', max_length=100, verbose_name='Шифр работы')),
                ('title', models.CharField(help_text='Полное наименование темы работы', max_length=500, verbose_name='Тема работы')),
                ('purpose', models.TextField(help_text='Основные цели и задачи работы', verbose_name='Цель работы')),
                ('is_active', models.BooleanField(default=True, help_text='Отметка актуальности данной версии ТЗ', verbose_name='Актуальная версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('contract', models.ForeignKey(help_text='Контракт, к которому относится техническое задание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_specifications', to='rnd.contract', verbose_name='Контракт')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Связь с предыдущей версией технического задания', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='rnd.technicalspecification', verbose_name='Предыдущая версия')),
                ('type', models.ForeignKey(help_text='Тип научно-исследовательских работ', on_delete=django.db.models.deletion.PROTECT, related_name='technical_specifications', to='rnd.rndtype', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Техническое задание',
                'verbose_name_plural': 'Технические задания',
                'ordering': ['contract', '-is_active', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RnDTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения задачи в списке', verbose_name='Порядковый номер')),
                ('description', models.TextField(help_text='Подробное описание задачи и требований к выполнению', verbose_name='Описание задачи')),
                ('is_completed', models.BooleanField(default=False, help_text='Отметка о выполнении задачи', verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('technical_specification', models.ForeignKey(help_text='Техническое задание, к которому относится задача', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='rnd.technicalspecification', verbose_name='Техническое задание')),
            ],
            options={
                'verbose_name': 'Задача НИОКР',
                'verbose_name_plural': 'Задачи НИОКР',
                'ordering': ['technical_specification', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RnD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', help_text='Текущий статус выполнения НИОКР', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('contract', models.OneToOneField(help_text='Контракт, по которому ведется НИОКР', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd', to='rnd.contract', verbose_name='Контракт')),
                ('technical_specification', models.ForeignKey(help_text='Актуальная версия технического задания для работы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_projects', to='rnd.technicalspecification', verbose_name='Активное техническое задание')),
            ],
            options={
                'verbose_name': 'НИОКР',
                'verbose_name_plural': 'НИОКР',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['number'], name='rnd_contrac_number_29b29b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['type'], name='rnd_contrac_type_id_07ab47_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalspecification',
            index=models.Index(fields=['contract', 'is_active'], name='rnd_technic_contrac_80c1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalspecification',
            index=models.Index(fields=['code'], name='rnd_technic_code_a834b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalspecification',
            unique_together={('contract', 'code')},
        ),
        migrations.AddIndex(
            model_name='rndtask',
            index=models.Index(fields=['technical_specification', 'is_completed'], name='rnd_rndtask_technic_ad91b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rndtask',
            unique_together={('technical_specification', 'order')},
        ),
        migrations.AddIndex(
            model_name='rnd',
            index=models.Index(fields=['contract'], name='rnd_rnd_contrac_4168da_idx'),
        ),
        migrations.AddIndex(
            model_name='rnd',
            index=models.Index(fields=['status'], name='rnd_rnd_status_96bbe5_idx'),
        ),
    ]
