# Generated by Django 5.0 on 2026-02-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnd',
            options={'ordering': ['contract__number'], 'verbose_name': 'НИОКР', 'verbose_name_plural': 'НИОКР'},
        ),
        migrations.RemoveField(
            model_name='rnd',
            name='technical_specification',
        ),
        migrations.AddField(
            model_name='rnd',
            name='contract',
            field=models.ForeignKey(help_text='Договор, к которому относится НИОКР', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnd_contracts', to='rnd.contract', verbose_name='ГК / договор'),
        ),
    ]
