# Generated by Django 5.0 on 2026-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RnDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Тип НИОКР', max_length=255, verbose_name='Тип НИОКР')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Тип НИОКР',
                'verbose_name_plural': 'Типы НИОКР',
                'ordering': ['id'],
            },
        ),
    ]
