# Generated by Django 5.0 on 2026-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0002_rndtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rndtype',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='rndtype',
            name='short_name',
            field=models.CharField(default=1, help_text='Тип НИОКР (полностью)', max_length=255, verbose_name='Тип НИОКР (полностью)'),
            preserve_default=False,
        ),
    ]
