# Generated by Django 5.0 on 2026-02-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0003_rename_type_rndtype_name_rndtype_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnd',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnd_type', to='rnd.rndtype', verbose_name='Тип НИОКР'),
        ),
    ]
