# Generated by Django 5.0 on 2026-02-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0004_rnd_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rnd',
            options={'ordering': ['code'], 'verbose_name': 'НИОКР', 'verbose_name_plural': 'НИОКР'},
        ),
    ]
